[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd backend && npm ci --include=dev"]

[phases.build]
cmds = ["cd backend && npm run build"]

[start]
cmd = "cd backend && node dist/index.js"
